// <auto-generated />
using System;
using DiskSpaceTree.Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiskSpaceTree.Data.Migrations
{
    [DbContext(typeof(ScanDbContext))]
    [Migration("20260818141448_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.19");

            modelBuilder.Entity("DiskSpaceTree.Data.Entities.Directory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedAtExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FirstSeenExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("LastSeenExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentDirectoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAtExecutionId");

                    b.HasIndex("FirstSeenExecutionId");

                    b.HasIndex("LastSeenExecutionId");

                    b.HasIndex("ParentDirectoryId");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("Directories");
                });

            modelBuilder.Entity("DiskSpaceTree.Data.Entities.DirectoryInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("DirectFileCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DirectSizeInKb")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DirectoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasError")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeletedSnapshot")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeInKb")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.HasIndex("DirectoryId", "ExecutionId")
                        .IsUnique();

                    b.ToTable("DirectoryInfos");
                });

            modelBuilder.Entity("DiskSpaceTree.Data.Entities.Execution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalDirectoriesFound")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalFilesProcessed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Executions");
                });

            modelBuilder.Entity("DiskSpaceTree.Data.Entities.Directory", b =>
                {
                    b.HasOne("DiskSpaceTree.Data.Entities.Execution", "DeletedAtExecution")
                        .WithMany("DeletedAtDirectories")
                        .HasForeignKey("DeletedAtExecutionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiskSpaceTree.Data.Entities.Execution", "FirstSeenExecution")
                        .WithMany("FirstSeenDirectories")
                        .HasForeignKey("FirstSeenExecutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiskSpaceTree.Data.Entities.Execution", "LastSeenExecution")
                        .WithMany("LastSeenDirectories")
                        .HasForeignKey("LastSeenExecutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiskSpaceTree.Data.Entities.Directory", "ParentDirectory")
                        .WithMany("Children")
                        .HasForeignKey("ParentDirectoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DeletedAtExecution");

                    b.Navigation("FirstSeenExecution");

                    b.Navigation("LastSeenExecution");

                    b.Navigation("ParentDirectory");
                });

            modelBuilder.Entity("DiskSpaceTree.Data.Entities.DirectoryInfo", b =>
                {
                    b.HasOne("DiskSpaceTree.Data.Entities.Directory", "Directory")
                        .WithMany("Infos")
                        .HasForeignKey("DirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiskSpaceTree.Data.Entities.Execution", "Execution")
                        .WithMany("DirectoryInfos")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Directory");

                    b.Navigation("Execution");
                });

            modelBuilder.Entity("DiskSpaceTree.Data.Entities.Directory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Infos");
                });

            modelBuilder.Entity("DiskSpaceTree.Data.Entities.Execution", b =>
                {
                    b.Navigation("DeletedAtDirectories");

                    b.Navigation("DirectoryInfos");

                    b.Navigation("FirstSeenDirectories");

                    b.Navigation("LastSeenDirectories");
                });
#pragma warning restore 612, 618
        }
    }
}
